import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { resolveTasksUrl } from './task-config.ts';
import {
  normalizeTaskText,
  parseCreatedTaskId,
  parseTaskCollection,
  TASK_TEXT_MAX_LENGTH,
} from './task-data.ts';

describe('normalizeTaskText', () => {
  it('trims leading and trailing whitespace', () => {
    assert.equal(normalizeTaskText('  Finish the task  '), 'Finish the task');
  });

  it('rejects empty text', () => {
    assert.throws(() => normalizeTaskText('   '), /cannot be empty/);
  });

  it('rejects text that exceeds the character limit', () => {
    assert.throws(
      () => normalizeTaskText('a'.repeat(TASK_TEXT_MAX_LENGTH + 1)),
      /cannot exceed 160 characters/,
    );
  });
});

describe('parseTaskCollection', () => {
  it('converts an empty Firebase response into an empty list', () => {
    assert.deepEqual(parseTaskCollection(null), []);
  });

  it('parses valid tasks and supports legacy records', () => {
    assert.deepEqual(
      parseTaskCollection({
        first: { text: 'Finish the report', completed: true },
        second: { text: 'Join the meeting' },
      }),
      [
        { id: 'first', text: 'Finish the report', completed: true },
        { id: 'second', text: 'Join the meeting', completed: false },
      ],
    );
  });

  it('ignores malformed task records', () => {
    assert.deepEqual(
      parseTaskCollection({
        valid: { text: 'Valid' },
        invalid: { text: 42 },
        empty: { text: '   ' },
      }),
      [{ id: 'valid', text: 'Valid', completed: false }],
    );
  });

  it('rejects a response that is not a collection', () => {
    assert.throws(() => parseTaskCollection([]), /invalid task data/);
  });
});

describe('parseCreatedTaskId', () => {
  it('returns the ID generated by Firebase', () => {
    assert.equal(parseCreatedTaskId({ name: 'task-123' }), 'task-123');
  });

  it('rejects an invalid ID', () => {
    assert.throws(() => parseCreatedTaskId({ name: '' }), /valid ID/);
  });
});

describe('resolveTasksUrl', () => {
  it('normalizes a valid Firebase collection URL', () => {
    assert.equal(
      resolveTasksUrl(' https://example-default-rtdb.firebaseio.com/tasks.json/ '),
      'https://example-default-rtdb.firebaseio.com/tasks.json',
    );
  });

  it('accepts HTTP only for local emulators', () => {
    assert.equal(
      resolveTasksUrl('http://127.0.0.1:9000/tasks.json'),
      'http://127.0.0.1:9000/tasks.json',
    );
    assert.throws(
      () => resolveTasksUrl('http://example.com/tasks.json'),
      /must use HTTPS/,
    );
  });

  it('rejects missing, malformed, and incorrectly scoped URLs', () => {
    assert.throws(() => resolveTasksUrl(''), /not configured/);
    assert.throws(() => resolveTasksUrl('not-a-url'), /valid URL/);
    assert.throws(
      () => resolveTasksUrl('https://example.com/other.json'),
      /must end with \/tasks.json/,
    );
  });
});
